### ISSUE TITLE
How encoder side embeddings are fed to the LLM

### ISSUE THREAD

**Issue by chiho-5** [NExT-GPT/NExT-GPT.github.io#2]
Hi. I came across the paper on NExT-GPT that was recently released. I've got to say that it's quite an interesting project and I can't wait to build on it. I'm trying to understand how the encoder side embeddings are fed to the LLM. Since each embedding from imageBind is projected to its own linear layer, then are these embeddings fed all at once to the LLM during training or are they trained sequentially?

**Comment by ChocoWu** [comment]
Hi, thx for your attention.  

Since the ImageBind is aligned across multiple modalities, the truth is that we just need to devise one input projection layer for all different modalities to obtain the representations.  
So, the embeddings of any modality from ImageBind are fed into LLM together all at once.

For more details, please check the [code](https://github.com/NExT-GPT/NExT-GPT).

**Comment by chiho-5** [comment]
Oh thanks. This makes more sense. I've checked the codes and it's more understandable now. It seems like the image in the research paper is supposed to show  like a vanilla approach(if imageBind is not considered).
